services:
    redis-node-1:
        image: redis
        container_name: redis-node-1
        command: redis-server --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --appendonly yes
        ports:
            - "6379:6379"
            - "16379:16379"
        volumes:
            - redis-node-1-data:/data

    redis-node-2:
        image: redis
        container_name: redis-node-2
        command: redis-server --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --appendonly yes
        ports:
            - "6380:6379"
            - "16380:16379"
        volumes:
            - redis-node-2-data:/data

    redis-node-3:
        image: redis
        container_name: redis-node-3
        command: redis-server --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --appendonly yes
        ports:
            - "6381:6379"
            - "16381:16379"
        volumes:
            - redis-node-3-data:/data

    redis-node-4:
        image: redis
        container_name: redis-node-4
        command: redis-server --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --appendonly yes
        ports:
            - "6382:6379"
            - "16382:16379"
        volumes:
            - redis-node-4-data:/data

    redis-node-5:
        image: redis
        container_name: redis-node-5
        command: redis-server --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --appendonly yes
        ports:
            - "6383:6379"
            - "16383:16379"
        volumes:
            - redis-node-5-data:/data

    redis-node-6:
        image: redis
        container_name: redis-node-6
        command: redis-server --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --appendonly yes
        ports:
            - "6384:6379"
            - "16384:16379"
        volumes:
            - redis-node-6-data:/data

    python-project:
        build: .
        container_name: python-project
        profiles:
            - testing
        ports:
            - "4000:4000"
        depends_on:
            - redis-node-1
            - redis-node-2
            - redis-node-3
            - redis-node-4
            - redis-node-5
            - redis-node-6

volumes:
    redis-node-1-data:
    redis-node-2-data:
    redis-node-3-data:
    redis-node-4-data:
    redis-node-5-data:
    redis-node-6-data:
